"use client"
import Head from "next/head";
import { Inter } from "next/font/google";
import Dashboard from "./admin/default/Home/Home";
import "../styles/Home.module.css";
import LoginLayout from "./Login/LoginLayout";
import App from "./App";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  /* const [authsession, setSession] = useState(null);
useEffect(()=>{ 
const session = supabase.auth.session()
  setSession(session)
},[])*/
  return (
    <>
      <Head>
        <title>TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginLayout />

      <App/>
    </>
  );
}
