import Head from 'next/head'
import { Inter } from 'next/font/google'
import Dashboard from './admin/Dashboard'
import '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

/* const [authsession, setSession] = useState(null);
useEffect(()=>{ 
const session = supabase.auth.session()
  setSession(session)
},[])*/ 
  return (
    <>
    
      <Head>
        <title>TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard/>
    
       
      
    
    </>
  )
}

{/* const Home = ({ user }) => {
  return (
    <MainLayout>
      <div className="container-wrapper">{!user ? <UserNotLogged /> : <HomeContainer />}</div>
      <style jsx>
        {`
          .container-wrapper {
            width: 100%;
            margin-top: 80px;
          }
        `}
      </style>
    </MainLayout>
  );
};

Home.propTypes = {
  user: PropTypes.object,
};

export default withUser(Home); */}
